# Use the official MongoDB image
FROM mongo

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=mongoadmin
ENV MONGO_INITDB_DATABASE=product_app

# Expose the default MongoDB port
EXPOSE 27017
